app <- ShinyDriver$new("../../")
app$snapshotInit("register")

app$setInputs(`login_system-register_bttn` = "click")
app$snapshot()
app$setInputs(`login_system-register_user_ID` = "Testing_RegLog")
app$setInputs(`login_system-register_email` = "testingexample.com")
app$setInputs(`login_system-register_pass1` = "RegLog")
app$setInputs(`login_system-register_pass2` = "RegLog")
app$setInputs(`login_system-register_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-register_user_ID` = "TestingRegLog")
app$setInputs(`login_system-register_pass1` = "RegLog")
app$setInputs(`login_system-register_pass2` = "RegLog")
app$setInputs(`login_system-register_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-register_email` = "statismike@gmail.com")
app$setInputs(`login_system-register_pass1` = "RegLog")
app$setInputs(`login_system-register_pass2` = "RegLog")
app$setInputs(`login_system-register_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-register_pass2` = "RegLog")
app$setInputs(`login_system-register_pass1` = "RegLogTest1")
app$setInputs(`login_system-register_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-register_pass1` = "RegLogTest1")
app$setInputs(`login_system-register_pass2` = "RegLogTest1")
app$setInputs(`login_system-register_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-register_user_ID` = "TestingRegLog")
app$setInputs(`login_system-register_email` = "testing2@example.com")
app$setInputs(`login_system-register_pass1` = "RegLogTest1")
app$setInputs(`login_system-register_pass2` = "RegLogTest1")
app$setInputs(`login_system-register_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-register_user_ID` = "TestingRegLog2")
app$setInputs(`login_system-register_email` = "statismike@gmail.com")
app$setInputs(`login_system-register_pass1` = "RegLogTest1")
app$setInputs(`login_system-register_pass2` = "RegLogTest1")
app$setInputs(`login_system-register_bttn` = "click", timeout_ = 10000)
app$snapshot()
