app <- ShinyDriver$new("../../", seed = 2137)
app$snapshotInit("mytest")
app$setInputs(`login_system-register_user_ID` = "vermin414")
app$setInputs(`login_system-register_email` = "statismike@gmail.com")
app$setInputs(`login_system-register_pass1` = "vermin414")
app$setInputs(`login_system-register_pass2` = "vermin414")
app$setInputs(`login_system-register_bttn` = "click", timeout_ = 10000)
app$waitFor("($('#shiny-modal').data('bs.modal') || {}).isShown")
Sys.sleep(2)
app$snapshot()
app$executeScript("$('.modal').modal('hide');")
app$setInputs(tabset = "Login")
app$setInputs(`login_system-login_user_id` = "vermin")
app$setInputs(`login_system-password_login` = "vermin")
app$setInputs(`login_system-login_button` = "click", timeout_ = 10000)
app$waitFor("($('#shiny-modal').data('bs.modal') || {}).isShown")
Sys.sleep(2)
app$snapshot()
app$executeScript("$('.modal').modal('hide');")
app$setInputs(`login_system-login_user_id` = "vermin414")
app$setInputs(`login_system-password_login` = "vermin")
app$setInputs(`login_system-login_button` = "click", timeout_ = 10000)
app$waitFor("($('#shiny-modal').data('bs.modal') || {}).isShown")
Sys.sleep(2)
app$snapshot()
app$executeScript("$('.modal').modal('hide');")
app$setInputs(`login_system-login_user_id` = "vermin414")
app$setInputs(`login_system-password_login` = "vermin414")
app$setInputs(`login_system-login_button` = "click", timeout_ = 10000)
app$waitFor("($('#shiny-modal').data('bs.modal') || {}).isShown")
Sys.sleep(2)
app$snapshot()
app$executeScript("$('.modal').modal('hide');")
app$setInputs(`login_system-logout_bttn` = "click", timeout_ = 10000)
app$setInputs(`login_system-logout_accept` = "click", timeout_ = 10000)
# app$setInputs(`login_system-logout_accept` = "click", timeout_ = 10000)
app$waitFor("($('#shiny-modal').data('bs.modal') || {}).isShown")
Sys.sleep(2)
app$snapshot()
app$executeScript("$('.modal').modal('hide');")
app$setInputs(tabset = "Password reset")
app$setInputs(`login_system-resetpass_user_ID` = "vermin414")
app$setInputs(`login_system-resetpass_send` = "click", timeout_ = 10000)
app$waitFor("($('#shiny-modal').data('bs.modal') || {}).isShown")
Sys.sleep(2)
app$snapshot()
app$executeScript("$('.modal').modal('hide');")
app$setInputs(`login_system-resetpass_code` = "2018234753")
app$setInputs(`login_system-resetpass_code_bttn` = "click", timeout_ = 10000)
app$waitFor("($('#shiny-modal').data('bs.modal') || {}).isShown")
Sys.sleep(2)
app$snapshot()
# app$setInputs(`login_system-resetpass1` = "", wait_ = FALSE)
# app$setInputs(`login_system-resetpass2` = "", wait_ = FALSE)
app$setInputs(`login_system-resetpass1` = "vermin415")
app$setInputs(`login_system-resetpass2` = "vermin415")
app$setInputs(`login_system-resetpass_modal_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$executeScript("$('.modal').modal('hide');")
app$setInputs(tabset = "Login")
app$setInputs(`login_system-login_user_id` = "vermin414")
app$setInputs(`login_system-password_login` = "vermin415")
app$setInputs(`login_system-login_button` = "click", timeout_ = 10000)
app$waitFor("($('#shiny-modal').data('bs.modal') || {}).isShown")
Sys.sleep(2)
app$snapshot()
app$executeScript("$('.modal').modal('hide');")
app$setInputs(`login_system-logout_bttn` = "click", timeout_ = 10000)
app$setInputs(`login_system-logout_accept` = "click", timeout_ = 10000)
# app$setInputs(`login_system-logout_accept` = "click", timeout_ = 10000)
app$waitFor("($('#shiny-modal').data('bs.modal') || {}).isShown")
Sys.sleep(2)
app$snapshot()
app$executeScript("$('.modal').modal('hide');")

