app <- ShinyDriver$new("../../", seed = 2137)
app$snapshotInit("resetPass")

app$setInputs(reglogtabset = "Password reset")
app$setInputs(`login_system-reset_send` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-reset_user_ID` = "Testing_RegLog")
app$setInputs(`login_system-reset_send` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-reset_user_ID` = "TestingRegLog")
app$setInputs(`login_system-reset_send` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-reset_confirm_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-reset_user_ID` = "TestingRegLog")
app$setInputs(`login_system-reset_code` = "1234567890")
app$setInputs(`login_system-reset_pass1` = "RegLog")
app$setInputs(`login_system-reset_pass2` = "RegLog")
app$setInputs(`login_system-reset_confirm_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-reset_pass2` = "RegLog")
app$setInputs(`login_system-reset_pass1` = "RegLogTest2")
app$setInputs(`login_system-reset_confirm_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-reset_pass1` = "RegLogTest2")
app$setInputs(`login_system-reset_pass2` = "RegLogTest2")
app$setInputs(`login_system-reset_confirm_bttn` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(`login_system-reset_user_ID` = "TestingRegLog")
app$setInputs(`login_system-reset_code` = "2018234753")
app$setInputs(`login_system-reset_pass1` = "RegLogTest2")
app$setInputs(`login_system-reset_pass2` = "RegLogTest2")
app$setInputs(`login_system-reset_confirm_bttn` = "click", timeout_ = 10000)
app$snapshot()
